# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
# on dispatch, and weekly on Sunday at 00:00 UTC (midnight)
---
name: Download davinci-resolve
on: { workflow_dispatch: {}, schedule: [{ cron: "0 0 * * 0" }] }

concurrency: { group: "puppeteer-${{ github.ref_name }}", cancel-in-progress: true }
permissions: { contents: read }

jobs:
  download:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with: { persist-credentials: false }
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with: { node-version-file: .node-version }
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
        with: { bun-version: canary }
      - uses: kjanat/runner@d166c6d1b70147ed7c4a2fdb0e4ed5ed8d2e4d39 # master
      - run: runner install --frozen dr-downloader
      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: davinci-resolve
          path: downloads/
          retention-days: 2
          if-no-files-found: warn
